name: Python application

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4 # Updated to latest version
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env: # Add environment variable setup if needed
        API_KEY: ${{ secrets.API_KEY }} # Example for sensitive API keys
      run: |
        python -m unittest discover # Discover all test modules and execute them
